---
- name: create susrvey dropdown listbox for inventories associated with job templates
  hosts: all
  ignore_errors: true
  vars:
    jt_string: "{{ job_template_string  | default('backup') }}"

  tasks: 
    - name: Find inventories with set_fact
      set_fact:
        inventories: >-
          {{
            inventories | default([]) +
            [{
              'job_template_name': item['name'],
              'id': item['id'],
              'inventory_name': item['summary_fields']['inventory']['name'],
              'inventory_id': item['summary_fields']['inventory']['id'],
              'hosts': query('ansible.controller.controller_api', 'hosts') | json_query('[?summary_fields.inventory.id == `' + item.summary_fields.inventory.id | string + '`].name') | default([])
            }]
          }}
      loop: "{{ query('ansible.controller.controller_api', 'job_templates', query_params={ 'name__iregex': '.' + jt_string + '.*' }) }}"

    - name: show inventories
      debug:
        var: inventories

######Sample Output
######
######{
######  "inventories": [
######    {
######      "job_template_name": "AAP Backup",
######      "id": 22,
######      "inventory_name": "AWS Running Inventory",
######      "inventory_id": 2,
######      "hosts": [
######        "ec2-3-208-4-54.compute-1.amazonaws.com",
######        "ec2-34-234-101-31.compute-1.amazonaws.com",
######        "ec2-34-236-8-30.compute-1.amazonaws.com",
######        "ec2-44-215-214-41.compute-1.amazonaws.com",
######        "ec2-54-85-47-74.compute-1.amazonaws.com"
######      ]
######    }
######  ],
######  "_ansible_verbose_always": true,
######  "_ansible_no_log": null,
######  "changed": false
######}


#  - name: use inventories variable to inject values into jinja2 template that defines how the survey_spec should be defined

    - name: build hosts surveys in job templates
      debug:
        var: "{{ ansible_loop }}"
      loop: "{{ inventories }}"
      loop_control:
        loop_var: ansible_loop

#     example https://github.com/network-automation/toolkit/blob/master/playbooks/network_backup.yml
    - name: build hosts surveys in job templates
      ansible.controller.job_template:
        name: "{{ item.job_template_name }}"
        job_type: "run"
        survey_enabled: true
        survey_spec: "{{ lookup('template', '{{ playbook_dir }}/templates/host_field_survey_specs.j2') }}"
        vars:
          ansible_loop_index: "{{ loop_index }}"
      loop: "{{ inventories }}"
