---
- name: create susrvey dropdown listbox for inventories associated with job templates
  hosts: all
  ignore_errors: true
  vars:
    jt_string: "{{ job_template_string  | default('backup') }}"

  tasks: 
    - name: Find inventories with set_fact
      set_fact:
        inventories: >-
          {{
            inventories | default([]) +
            [{
              'name': item['name'],
              'id': item['id'],
              'inventory_name': item['summary_fields']['inventory']['name'],
              'inventory_id': item['summary_fields']['inventory']['id'],
              'hosts': query('ansible.controller.controller_api', 'hosts') | json_query('[?summary_fields.inventory.id == `' + item.summary_fields.inventory.id | string + '`].name') | default([])
            }]
          }}
      loop: "{{ query('ansible.controller.controller_api', 'job_templates', query_params={ 'name__iregex': '.' + jt_string + '.*' }) }}"

    - name: show inventories
      debug:
        var: inventories

    - name: Get hosts with controller_api query and store in inventory_hosts
      set_fact:
        inventory_hosts: "{{ query('ansible.controller.controller_api', 'hosts') | json_query('[?summary_fields.inventory.id == `3`].name') | default([])}}"
    # instead of hardcoding 3, the idea is to loop through jobs_and_inventories and filter by each inventory ID and append that list in the jobs_and_inventories dictionary/list which will later be used to build the survey within each job template. 
    # note: you will likely want to filter job templates so that a survey is not added to every job_template.


  #  - name: use jobs_and_inventories to get inventory hosts and groups

    # example https://github.com/network-automation/toolkit/blob/master/playbooks/network_backup.yml
    #- name: build hosts surveys in job templates
    #  ansible.controller.job_template:
    #    name: "Network Automation - Restore"
    #    job_type: "run"
    #    inventory: "{{ restore_inventory | default('Network Inventory') }}"
    #    project: "{{ restore_project | default('Network Toolkit') }}"
    #    playbook: "{{ restores_playbook | default('playbooks/network_restore.yml') }}"
    #    credential: "{{ restore_credential | default('Network Credential') }}"
    #    survey_enabled: true
    #    survey_spec: "{{ lookup('template', '{{ playbook_dir }}/templates/backup.j2') }}"
    #    validate_certs: false
    #    execution_environment: "Default execution environment"
    #  run_once: true
