---
- name: create susrvey dropdown listbox for inventories associated with job templates
  hosts: all
  ignore_errors: true
  vars:
    jt_string: "{{ job_template_string }}"
  tasks:                                                                                 
    - name: Report the usernames of all users with admin privs                                                                                  
      debug:                                                                                                                                    
        msg: "Admin users: {{ query('ansible.controller.controller_api', 'users', query_params={ 'is_superuser': true }) | map(attribute='username') | join
                                                                                                                                                
#    - name: debug all organizations in a loop  # use query to return a list                                                                     
#      debug:                                                                                                                                    
#        msg: "Organization description={{ item['description'] }} id={{ item['id'] }}"                                                           
#      loop: "{{ query('awx.awx.controller_api', 'job_templates') }}"                                                                            
#      loop_control:                                                                                                                            ▒
#        label: "{{ item['name'] }}" 

